server:
  port: ${BPD_CITIZEN_PORT:8080}
  tomcat:
    connection-timeout: ${BPD_CITIZEN_SERVER_CONNECTION_TIMEOUT:${SERVER_CONNECTION_TIMEOUT:}}
    max-connections: ${BPD_CITIZEN_SERVER_MAX_CONNECTION:${SERVER_MAX_CONNECTION:8192}}
    processor-cache: ${BPD_CITIZEN_SERVER_PROCESSOR_CACHE:${SERVER_PROCESSOR_CACHE:200}}
    threads.max: ${BPD_CITIZEN_SERVER_THREAD_MAX:${SERVER_THREAD_MAX:200}}
    threads.min-spare: ${BPD_CITIZEN_SERVER_THREAD_MIN:${SERVER_THREAD_MIN:10}}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable italian documentations
      - swaggerIT

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

error-manager:
  enabled: true

meda:
  core:
    sessioncontext:
      enabled: false

logging:
  level:
    it.gov.pagopa.bpd.citizen: ${LOG_LEVEL_CITIZEN:DEBUG}
    com.zaxxer.hikari.HikariConfig: ${LOG_LEVEL_BPD_CITIZEN_DATASOURCE_POOL_CONFIG:OFF}
    com.zaxxer.hikari.pool.HikariPool: ${LOG_LEVEL_BPD_CITIZEN_DATASOURCE_POOL:OFF}
    org.hibernate.stat: ${LOG_LEVEL_BPD_CITIZEN_HIBERNATE_STAT:OFF}
    org.hibernate.SQL:  ${LOG_LEVEL_BPD_CITIZEN_HIBERNATE_SQL:OFF}
