server:
  port: ${DEMO_PORT:8082}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

error-manager:
  enabled: true

logging:
  level:
    eu.sia.bpd.demo: ${LOG_LEVEL_DEMO:DEBUG}