apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bpdmscitizen 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bpdmscitizen 
    spec:
      containers:
        - name: bpdmscitizen 
          image: cstarregistry.azurecr.io/bpdmscitizen
          ports:
          - containerPort: 8080
          envFrom:
          - secretRef:
            name: postgres-credentials
          - configMapRef:
            name: eventhub-logging
