apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmscitizen
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: bpdmscitizen
  template:
    metadata:
      labels:
        app: bpdmscitizen
    spec:
      containers:
        - name: bpdmscitizen
          image: cstarprodregistry.azurecr.io/bpdmscitizen
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: bpdmscitizen
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: bpdmscitizen
            - configMapRef:
                name: jvm                
      hostAliases:
        - hostnames:
            - u87cstarprod.servicebus.windows.net
          ip: 10.70.132.4
