apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bpdmscitizen 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bpdmscitizen 
    spec:
      containers:
        - name: bpdmscitizen
          image: cstarregistry.azurecr.io/bpdmscitizen-sit
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: bpdmscitizen
      hostAliases:
        - hostnames:
            - bpd-hub-dev.servicebus.windows.net
          ip: 10.70.5.9