apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmscitizen
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: bpdmscitizen
  template:
    metadata:
      labels:
        app: bpdmscitizen
    spec:
      containers:
        - name: bpdmscitizen
          image: cstaruatregistry.azurecr.io/bpdmscitizen
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: bpdmscitizen
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: bpdmscitizen
            - configMapRef:
                name: jvm
          resources:
            limits:
              cpu: 800m
              memory: 4Gi
            requests:
              cpu: 10m
              memory: 256Mi
      hostAliases:
        - hostnames:
            - bpd-event-uat.servicebus.windows.net
          ip: 10.70.67.5
