# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - features/*
      - hotfix/*
  paths:
    include:
      - api/*
      - app/*
      - core/*
      - integration/*
      - pom.xml

pool:
  vmImage: ubuntu-latest

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  dockerfileRelativePath: 'Dockerfile'

  # Agent VM image name for Build
  vmImageNameDefault: 'ubuntu-latest'

  # Image Repository Name
  imageRepository: 'bpdmscitizen'
  isToDeploy: $[and(ne(variables['Build.Reason'], 'PullRequest'), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix')))]
  isSIT: $[eq(variables['Build.SourceBranch'], 'refs/heads/release/st')]
  isUAT: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/release/uat'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))]
  isPROD: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
steps:
#  - task: Cache@2
#    inputs:
#      key: 'maven | "$(Agent.OS)" | pom.xml'
#      restoreKeys: |
#        maven | "$(Agent.OS)"
#        maven
#      path: $(MAVEN_CACHE_FOLDER)
#    displayName: Cache Maven local repo

#  - task: SonarCloudPrepare@1
#    displayName: 'Prepare SonarCloud analysis configuration'
#    inputs:
#      SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
#      organization: '$(SONARCLOUD_ORG)'
#      scannerMode: Other
#      extraProperties: |
#        sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
#        sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
#        sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
#        sonar.junit.reportPaths=target/surefire-reports/

  - task: DownloadSecureFile@1
      displayName: 'download settings.xml for Maven'
      name: settingsxml
      inputs:
        secureFile: 'settings.xml'
        retryCount: '2'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
      options: '-B -s $(settingsxml.secureFilePath)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      mavenAuthenticateFeed: false
      effectivePomSkip: true
      sonarQubeRunAnalysis: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

#  - task: SonarCloudPublish@1
#    displayName: 'Publish SonarCloud results on build summary'
#    inputs:
#      pollingTimeoutSec: '300'